<a href="https://colab.research.google.com/github/sulthanalihsan/data-science-2026/blob/main/Pertemuan2_Muhamad_Sulthan_Al_Ihsan_250401020154.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
import pandas as pd

In [27]:
data = ["sulthan","zayna","satu","mama"]
print(data[1:4])

koord = (10.2,5.6)
print(koord[0])

['zayna', 'satu', 'mama']
10.2


In [28]:
produk = {"productName":"bangku","price":100000}
produk['description'] = "gasan beduduk"
print(produk['productName'])
print(produk['description'])

for key,value in produk.items():
  print(f'{key}: {value}');

bangku
gasan beduduk
productName: bangku
price: 100000
description: gasan beduduk


In [29]:
kota_a = {'Jakarta','Bandung','Surabaya'}
kota_b = {'Bandung','Medan','Bali'}
print(kota_a & kota_b)
print(kota_a | kota_b) # union
print(kota_a - kota_b) # difference

{'Bandung'}
{'Bali', 'Bandung', 'Surabaya', 'Jakarta', 'Medan'}
{'Surabaya', 'Jakarta'}


In [30]:
# Dari list Python
a1D = np.array([1, 2, 3, 4, 5]) # 1D
a2D = np.array([[1,2,3],[4,5,6]]) # 2D
#print(a1D[1])
#print(a2D[1][2]);
# Array dengan nilai inisial

zeros = np.zeros((3, 4)) # nol semua
#print("zeros " f'{zeros}')

ones = np.ones((2, 3)) # satu semua
#print("ones " f'{ones}')

eye = np.eye(4) # matriks identitas
# print("eye " f'{eye}')

full = np.full((2, 2), 7) # nilai konstan
print("full " f'{full}')

# Sequence
arange = np.arange(0, 20, 2) # 0,2,4,...18
linsp = np.linspace(0, 1, 11) # 11 titik merata
# Array acak (reproducible)
rng = np.random.default_rng(seed=42)
rand_int = rng.integers(0, 100, (3, 4))
print("rand_int " f'{rand_int}')

rand_flt = rng.normal(loc=0, scale=1, size=(100,))

full [[7 7]
 [7 7]]
rand_int [[ 8 77 65 43]
 [43 85  8 69]
 [20  9 52 97]]


In [31]:
# Operasi aritmetika vektorisasi
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a + b) # → [11 22 33 44 55]
print(a * b) # → [10 40 90 160 250]
print(a ** 2) # → [1 4 9 16 25]
# Universal functions (ufuncs)
np.sqrt(a) # akar kuadrat tiap elemen
np.exp(a) # eksponensial (e^x)
np.log(b) # logaritma natural
# Fungsi statistik
data = rng.normal(0, 1, 1000)
# print(data)
print(f'Mean: {np.mean(data):.4f}')
print(f'Std: {np.std(data):.4f}')
print(f'Min: {np.min(data):.4f}')
print(f'Max: {np.max(data):.4f}')
print(f'Q1: {np.percentile(data,25):.4f}')
print(f'Q3: {np.percentile(data,75):.4f}')

[11 22 33 44 55]
[ 10  40  90 160 250]
[ 1  4  9 16 25]
Mean: -0.0163
Std: 1.0008
Min: -3.6484
Max: 3.1789
Q1: -0.6897
Q3: 0.6163


In [32]:
# Series dari list — index default 0,1,2...
s1 = pd.Series([85, 92, 78, 95, 88])
# print(s1)
# print(s1[3])
# Series dengan index kustom
nilai = pd.Series(
[85, 92, 78, 95, 100],
index=['Alice','Bob','Caca','Dina','sulthan']
)
print(nilai['Bob']) # → 92
print(nilai['sulthan'])
print(nilai[nilai>80]) # filter
print(nilai.mean()) # → 87.5
# print(nilai.describe()) # statistik lengkap

92
100
Alice       85
Bob         92
Dina        95
sulthan    100
dtype: int64
90.0


In [33]:
data = {
'nama': ['Ali','Budi','Caca','Dina'],
'usia': [22, 25, 21, 23],
'kota': ['Jakarta','Bandung','Surabaya','Medan'],
'ipk': [3.8, 3.5, 3.9, 3.7]
}
df = pd.DataFrame(data)
# Informasi dasar
print(df.shape) # → (4, 4)
print(df.dtypes) # tipe data per kolom
print(df.columns) # nama-nama kolom

(4, 4)
nama     object
usia      int64
kota     object
ipk     float64
dtype: object
Index(['nama', 'usia', 'kota', 'ipk'], dtype='object')


In [34]:
# Menggunakan link raw agar bisa dibaca langsung oleh pandas
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

# 2. Eksplorasi dasar
print(df.shape) # (891, 12)
print(df.head()) # 5 baris pertama
print(df.tail(3)) # 3 baris terakhir
print(df.info()) # tipe & missing
print(df.describe()) # statistik deskriptif
# 3. Cek missing values
print(df.isnull().sum()) # per kolom
print(df.isnull().mean()) # proporsi %

# Menampilkan 5 data teratas untuk memastikan data termuat
df.head()

(891, 12)
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN    

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [35]:
selamat = df[df['Survived']==1]
wanita = df[df['Sex']=='female']
# print(f'selamat {selamat}')
# print(wanita.shape)
# Kondisi ganda dengan & dan |
filt = df[(df['Age']>18) &
(df['Pclass']==1)]
# Seleksi kolom tertentu
df[['Name','Age','Survived']]

,Name,Age,Survived
0,"Braund, Mr. Owen Harris",22.0,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1
2,"Heikkinen, Miss. Laina",26.0,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1
4,"Allen, Mr. William Henry",35.0,0
...,...,...,...
886,"Montvila, Rev. Juozas",27.0,0
887,"Graham, Miss. Margaret Edith",19.0,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,0
889,"Behr, Mr. Karl Howell",26.0,1


In [36]:
# .loc — label-based
df.loc[0, 'Name'] # row 0, kol Name
df.loc[0:4, 'Age':'Fare']
# .iloc — integer-based
df.iloc[0, 2] # baris 0, kolom 2
df.iloc[0:5, 0:3] # 5 baris, 3 kolom
# Modifikasi via .loc
df.loc[df['Age']<18, 'Kategori']= 'Anak-anak'

In [37]:
# query() — sintaksis SQL-like
df.query('Age > 18 and Pclass==1')
# # isin() — filter multi-nilai
# kota = ['Jakarta','Bandung']
# df[df['Kota'].isin(kota)]
# # str accessor
# df[df['Name'].str.contains('Miss')]
# df['Name'].str.lower()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Kategori
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,NaN
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,NaN
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,NaN
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,NaN
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,NaN
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,NaN
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,NaN


In [38]:
# GroupBy dasar
# Rata-rata usia per kelas penumpang
df.groupby('Pclass')['Age'].mean()
# Beberapa agregasi sekaligus
df.groupby('Pclass').agg(
jumlah=('Survived','count'),
selamat=('Survived','sum'),
rata_usia=('Age','mean')
)
# GroupBy multi-kolom
df.groupby(['Pclass','Sex'])['Survived'].mean().unstack()
# Pivot Table (seperti Excel pivot)
pd.pivot_table(df,
values='Survived',
index='Pclass', columns='Sex',
aggfunc='mean')

Sex,female,male
Pclass,,
1,0.968085,0.368852
2,0.921053,0.157407
3,0.500000,0.135447


In [39]:
# ① Muat Dataset Titanic
# URL = "https://raw.githubusercontent.com/","F8C79Edatasciencedojo/datasets/master/Titanic/Titanic.csv"
df = pd.read_csv(url)
# ② Eksplorasi Awal
print(df.shape, df.columns.tolist())
print(df.isnull().sum())
# ③ Filtering — Penumpang Wanita Kelas 1
wk1 = df[(df['Sex']=='female') &
(df['Pclass']==1)]
print(wk1['Survived'].mean(), wk1['Age'].mean())
# ④ Groupby — Tingkat Keselamatan per Kelas
hasil = df.groupby('Pclass').agg(
total=('PassengerId','count'),
selamat=('Survived','mean'),
).round(3)
print(hasil)

(891, 12) ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
0.9680851063829787 34.61176470588235
        total  selamat
Pclass                
1         216    0.630
2         184    0.473
3         491    0.242


**LATIHAN**

1. Muat Data Set

In [40]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# lihat data
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


2. Explorasi
- berapa baris/kolom? Kolom apa saja? Ada missing
values di mana?

In [42]:
# Jumlah baris dan kolom
print(f"baris kolom : {df.shape}")
# data tipe
print(f"data tipe : {df.dtypes}")
# daftar kolom
print(f"kolom : {df.columns.tolist()}")

# Jumlah missing kolom
missing_col = df.isnull().sum()

# Persentase missing values
persentase = (df.isnull().sum() / len(df) * 100).round(2)

# Gabung menjadi tabel
missing_df = pd.DataFrame({
    'Jumlah Missing': missing_col,
    'Persentase (%)': persentase
})

# Tampilkan hanya kolom yang punya missing values
print("Kolom dengan missing values:")
missing_df[missing_df['Jumlah Missing'] > 0]

baris kolom : (891, 12)
data tipe : PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object
kolom : ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
Kolom dengan missing values:


,Jumlah Missing,Persentase (%)
Age,177,19.87
Cabin,687,77.10
Embarked,2,0.22


4. Filtering  -
Filter penumpang wanita kelas 1. Berapa yang selamat?
Rata-rata usianya?

In [43]:
survive_persentage = np.mean(df['Survived'].values) * 100

print(f"Persentase Selamat (NumPy): {survive_persentage:.2f}%")

wanita_kelas1 = df[(df['Sex'] == 'female') & (df['Pclass'] == 1)]

print(f"Jumlah penumpang wanita kelas 1 : {len(wanita_kelas1)} orang")
print(f"Rata-rata usia                  : {wanita_kelas1['Age'].mean():.2f} tahun")
print(f"Jumlah yang selamat             : {wanita_kelas1['Survived'].sum()} orang")
print(f"Survival rate                   : {wanita_kelas1['Survived'].mean()*100:.2f}%")

# Tampilkan 10 baris pertama
wanita_kelas1[['Name', 'Age', 'Survived']].head(10)

Persentase Selamat (NumPy): 38.38%
Jumlah penumpang wanita kelas 1 : 94 orang
Rata-rata usia                  : 34.61 tahun
Jumlah yang selamat             : 91 orang
Survival rate                   : 96.81%


,Name,Age,Survived
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1
11,"Bonnell, Miss. Elizabeth",58.0,1
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",NaN,1
52,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",49.0,1
61,"Icard, Miss. Amelie",38.0,1
88,"Fortune, Miss. Mabel Helen",23.0,1
136,"Newsom, Miss. Helen Monypeny",19.0,1
151,"Pears, Mrs. Thomas (Edith Wearne)",22.0,1
166,"Chibnall, Mrs. (Edith Martha Bowerman)",NaN,1


5. Groupby & Agregasi - groupby('Pclass')['Survived'].mean() — kelas mana tingkat keselamatan tertinggi?

In [44]:
# 1. Mengelompokkan data berdasarkan 'Pclass' dan mengambil rata-rata dari kolom 'Survived'
tingkat_selamat_per_kelas = df.groupby('Pclass')['Survived'].mean()

# 2. Mengonversi ke persentase agar lebih mudah dibaca (opsional)
persentase_per_kelas = tingkat_selamat_per_kelas * 100

print("Tingkat Keselamatan per Kelas Penumpang:")
print(persentase_per_kelas)

# 3. Mencari kelas dengan tingkat keselamatan tertinggi secara otomatis
kelas_tertinggi = tingkat_selamat_per_kelas.idxmax()
nilai_tertinggi = tingkat_selamat_per_kelas.max() * 100

print(f"\nKelas dengan tingkat keselamatan paling tinggi adalah Kelas {kelas_tertinggi} dengan {nilai_tertinggi:.2f}%")


Tingkat Keselamatan per Kelas Penumpang:
Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

Kelas dengan tingkat keselamatan paling tinggi adalah Kelas 1 dengan 62.96%
